Feature
LoboArkano/Basic-HTML-Page-Structure pull request #1
Opened 2020-02-18 14:08 UTC by LoboArkano

2020-02-19 18:49 UTC, pelzolga123 requested changes
Project requires changes.

2020-02-19 18:49 UTC, pelzolga123 commented
## Hi Team! ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
### Your project looks :+1: amazing!

Here are the changes you need to make, before this project can be approved:
* [ ] check HTML markup with this [validator](https://validator.w3.org/#validate_by_upload). Now it shows one error in your project.
* [ ] Pull Request should have meaningful title and a short description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
#### Navigation bar
* [ ] Project should have a`<button>` tag that represents the search button ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/search_button_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/)) Right now it is just an image.
* [ ] Project should have at least three embedded images on the rightmost part of the navbar that represent icons and/or an avatar ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/icons_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/))
#### Video section
* [ ] Project should have like and dislike icons ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/video_like_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/)) Right now you have images there.
 * [ ] `Share` should be a button ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/video_share_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/))
* [ ] `Subscribe` should be a button ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/video_subscribe_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/))

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

2020-02-19 21:31 UTC, kobiyoyo requested changes
## Hi Team      ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, but there are a few more things required. 
### General
- [x] Pull request should have a meaning short description.
- [x] Check HTML markup with this validator https://validator.w3.org/#validate_by_upload.

## Video section
 - [x] The share should be a button (screenshot from Pathwright)
-  [x] Subscribe should be a button with styled text not image (screenshot from Pathwright)

### Make changes and submit another code review request.
*Happy coding*

2020-02-19 21:32 UTC, kobiyoyo commented on index.html
> +					<button style="border: none">
no inline CSS

2020-02-19 21:33 UTC, kobiyoyo commented on index.html
> +					<button style="border: none">
no inline CSS

2020-02-20 20:26 UTC, mosesogwo approved these changes
**Hi team. Good job making the requested changes:+1:. Your project is approved :heavy_check_mark:**.

You can now merge to master.

**Good luck in your next project:stars:**

2020-02-20 21:46 UTC, merged